import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Navbar */}
      <nav className="relative z-20 flex justify-between items-center p-4 bg-black shadow-2xl bg-opacity-50">
        <Link href="/">
          <h1 className="text-2xl text-white font-bold">PodVibe</h1>
        </Link>
      </nav>
      {children}</body>
    </html>
  );
}
